# Generated by Django 4.2.3 on 2023-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvhistory',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
