# Generated by Django 4.2.5 on 2023-09-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0002_csvhistory_is_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvhistory',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='csvhistory',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
